--REVISAMOS TIEMPO SIN INDICE
   EXPLAIN ANALYZE
SELECT * FROM ventas WHERE producto_id = 56;




--CREAMOS INDICE
CREATE INDEX idx_producto_id ON ventas (producto_id);


--REVISAMOS TIEMPO CON INDICE
EXPLAIN ANALYZE
SELECT * FROM ventas WHERE producto_id = 57;